# Generated by Django 4.2.1 on 2024-02-19 17:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_post_create_remove_post_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='create',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время добавления'),
        ),
    ]
